name: Update README Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch Current Badge
      run: |
        curl -o badge-latest.svg https://badge.fury.io/rb/interactify.svg

    - name: Compare Badges
      id: compare
      run: |
        if cmp -s badge-latest.svg .github/badge-cached.svg; then
          echo "Badges are identical, no update needed."
          echo "update_needed=false" >> $GITHUB_ENV
        else
          echo "Badges differ, update needed."
          echo "update_needed=true" >> $GITHUB_ENV
          cp badge-latest.svg .github/badge-cached.svg
        fi

    - name: Update README
      if: env.update_needed == 'true'
      run: |
        sed -i 's/interactify.svg)/interactify.svg?$(date +%s))/' README.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md .github/badge-cached.svg
        git commit -m "Update README badge"
        git push
